class SwiggyTest{

	public static void main(String fooddelivery[]){
	
	String foodName="Maggi";
	double priceOfFoodName = Swiggy.search(foodName);
	System.out.println("The food price is "+priceOfFoodName);
	double priceWithGivenQuantity1=Swiggy.search("Maggi",5);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity1);
	String foodName1="Roti";
	double priceOfFoodName1 = Swiggy.search(foodName1);
	System.out.println("The food price is "+priceOfFoodName1);
	double priceWithGivenQuantity2=Swiggy.search("Roti",1);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity2);
	System.out.println("------------------------");
	String foodName2="Rice";
	double priceOfFoodName2 = Swiggy.search(foodName2);
	System.out.println("The pizza price is "+priceOfFoodName2);
	double priceWithGivenQuantity3=Swiggy.search(foodName2,2);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity3);
	System.out.println("------------------------");
	String foodName3="Poha";
	double priceOfFoodName3 = Swiggy.search(foodName3);
	System.out.println("The food price is "+priceOfFoodName3);
	double priceWithGivenQuantity4=Swiggy.search(foodName3,3);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity4);
	System.out.println("------------------------");
	String foodName4="Egg curry";
	double priceOfFoodName4= Swiggy.search(foodName4);
	System.out.println("The food price is"+priceOfFoodName4);
	double priceWithGivenQuantity5=Swiggy.search(foodName4,4);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity5);
	System.out.println("------------------------");
	String foodName5="Veg noodle";
	double priceOfFoodName5 = Swiggy.search(foodName5);
	System.out.println("The food price is "+priceOfFoodName5);
	double priceWithGivenQuantity6=Swiggy.search(foodName5,6);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity6);
	System.out.println("------------------------");
	String foodName6="tomoto rice";
	double priceOfFoodName6 = Swiggy.search(foodName6);
	System.out.println("The food price is "+priceOfFoodName6);
	double priceWithGivenQuantity7=Swiggy.search(foodName6,7);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity7);
	System.out.println("------------------------");
	String foodName7="Dal fry";
	double priceOfFoodName7 = Swiggy.search(foodName7);
	System.out.println("The food price is "+priceOfFoodName7);
	double priceWithGivenQuantity8=Swiggy.search(foodName7,5);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity8);
	System.out.println("------------------------");
	String foodName8="jeera rice";
	double priceOfFoodName8 = Swiggy.search(foodName8);
	System.out.println("The food price is "+priceOfFoodName8);
	double priceWithGivenQuantity9=Swiggy.search(foodName8,7);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity9);
	System.out.println("------------------------");
	String foodName9="fish curry";
	double priceOfFoodName9 = Swiggy.search(foodName9);
	System.out.println("The food price is"+priceOfFoodName9);
	double priceWithGivenQuantity10=Swiggy.search(foodName9,8);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity10);
	System.out.println("------------------------");
	String foodName10="chill potato";
	double priceOfFoodName10 = Swiggy.search(foodName10);
	System.out.println("The food price is "+priceOfFoodName10);
	double priceWithGivenQuantity16=Swiggy.search(foodName10,5);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity16);
	System.out.println("------------------------");
	String foodName11="veg soup";
	double priceOfFoodName11= Swiggy.search(foodName11);
	System.out.println("The pizza price is "+priceOfFoodName11);
	double priceWithGivenQuantity11=Swiggy.search(foodName11,5);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity11);
	System.out.println("------------------------");
	String foodName12="paneer";
	double priceOfFoodName12 = Swiggy.search(foodName12);
	System.out.println("The food  price is "+priceOfFoodName12);
	double priceWithGivenQuantity12=Swiggy.search(foodName12,2);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity12);
	System.out.println("------------------------");
	String foodName13="curd rice";
	double priceOfFoodName13 = Swiggy.search(foodName13);
	System.out.println("The food price is "+priceOfFoodName13);
	double priceWithGivenQuantity13=Swiggy.search(foodName13,3);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity13);
	System.out.println("------------------------");
	String foodName14="thai rice";
	double priceOfFoodName14 = Swiggy.search(foodName14);
	System.out.println("Thefood price is "+priceOfFoodName14);
	double priceWithGivenQuantity14=Swiggy.search(foodName14,2);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity14);
	System.out.println("------------------------");
	String foodName15="fish fry";
	double priceOfFoodName15 = Swiggy.search(foodName15);
	System.out.println("The food  price is "+priceOfFoodName15);
	double priceWithGivenQuantity15=Swiggy.search(foodName15,5);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity15);
	System.out.println("------------------------");
	String foodName16="soda";
	double priceOfFoodName16 = Swiggy.search(foodName16);
	System.out.println("The food price is "+priceOfFoodName16);
	double priceWithGivenQuantity17=Swiggy.search(foodName16,2);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity17);
	System.out.println("------------------------");
	String foodName17="doi";
	double priceOfFoodName17 = Swiggy.search(foodName17);
	System.out.println("The food price is "+priceOfFoodName17);
	double priceWithGivenQuantity18=Swiggy.search(foodName17,5);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity18);
	System.out.println("------------------------");
	String foodName18="pani puri";
	double priceOfFoodName18 = Swiggy.search(foodName18);
	System.out.println("The food price is "+priceOfFoodName18);
	double priceWithGivenQuantity19=Swiggy.search(foodName18,5);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity19);
	System.out.println("------------------------");
	String foodName19="badam milk";
	double priceOfFoodName19 = Swiggy.search(foodName19);
	System.out.println("The food price is "+priceOfFoodName19);
	double priceWithGivenQuantity20=Swiggy.search(foodName19,3);
	System.out.println("The food price with Quantity"+priceWithGivenQuantity20);
	

	
	}

}